8 feature implementação da tela de configurações
Swift-Money-Management-Team-App/MoneyManagementApp pull request #21
Opened 2024-10-28 05:31 UTC by RafaelOsiro

### Issue
closes #8

### Description
This PR aims to add the `Settings` screen and another components. 

### File Change
- Settings-Settings-View: Add SwiftUI view implementation following the handoff
- Settings-Settings-View-Model: Add global links and getters method
- Settings-Components-About-Us: Add SwiftUI view implementation following the handoff
- Settings-About-Us-ViewModel: Add member team data and get method
- Settings-Components-Privacy-Policy: Add SwiftUI view implementation
- Settings-Components-Terms: Add SwiftUI view implementation
- Model-MemberTeamModel: Add new system model
- Components-Rows-Shared-Link-Row: Add view builder
- Components-Rows-ToggleRow: Add view builder
- Components-Text-Body-Text: Add view builder
- - Components-Text-Title-Text: Add view builder

### Screenshot
#### iPhone 16 Pro Max
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 01](https://github.com/user-attachments/assets/43366969-6d0d-4821-9340-f2da4624e47c)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 04](https://github.com/user-attachments/assets/7198bf52-65ae-413c-8504-1bccafce59b5)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 07](https://github.com/user-attachments/assets/c9f3e872-6c0e-43a8-8d4b-c0bfc34dd090)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 10](https://github.com/user-attachments/assets/a118fd1e-f6d5-4122-9750-8b11d32bead9)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 14](https://github.com/user-attachments/assets/bff61c7d-d5ee-4b0e-bbeb-a1429c3ce553)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-28 at 02 25 20](https://github.com/user-attachments/assets/83799edb-836c-413c-8bda-5a3482850b20)

2024-10-28 22:03 UTC, raquelsantoss requested changes

2024-10-28 22:05 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/Settings/Components/AboutUs.swift
> +            openURL(URL(string: linkedinUrl)!)
Aqui eu tenho certeza que estou usando um valor. Por isso que está sendo usado um wrapper. Serão valores fixos!

2024-10-28 22:32 UTC, raquelsantoss commented
@RafaelOsiro outro ponto, não criar mais nomes de  branchs que contenham acento:
![image](https://github.com/user-attachments/assets/d3129bb8-2148-434d-bfc4-4cef4ebd0fc0)

A mensagem "The head ref may contain hidden characters: "8-feature-implementa\u00E7\u00E3o-da-tela-de-configura\u00E7\u00F5es" indica que o nome da sua branch (head ref) contém caracteres especiais que foram codificados em Unicode. Especificamente, as sequências \u00E7, \u00E3 e \u00F5 representam letras acentuadas usadas em português (respectivamente ç, ã e õ).

**Impacto**

**Codificação de Caracteres:** Alguns sistemas de controle de versão e ferramentas CI/CD preferem nomes de branch sem caracteres especiais, pois eles podem ser interpretados de forma diferente dependendo do sistema e do software.
**Compatibilidade e Erros Potenciais:** Isso pode causar problemas em algumas plataformas ou scripts automatizados que não processam corretamente caracteres Unicode em nomes de branch.

2024-10-28 22:50 UTC, RafaelOsiro commented
> @RafaelOsiro outro ponto, não criar mais nomes de branchs que contenham acento: ![image](https://private-user-images.githubusercontent.com/80298086/380911889-d3129bb8-2148-434d-bfc4-4cef4ebd0fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTYwNDIsIm5iZiI6MTczMDE1NTc0MiwicGF0aCI6Ii84MDI5ODA4Ni8zODA5MTE4ODktZDMxMjliYjgtMjE0OC00MzRkLWJmYzQtNGNlZjRlYmQwZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIyNDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzM2MDMzZmMyNmIzOWI1ZjkzNDU4YWYxMmZhYWZlNTY0YmRmZDAyNWRkZTIxZmRhM2M5NDM1N2QxZmQ5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WnBHVs9hOAkJK2ljMUvxd6qWxagGVFlQvRhJmPTE-FM)
> 
> A mensagem "The head ref may contain hidden characters: "8-feature-implementa\u00E7\u00E3o-da-tela-de-configura\u00E7\u00F5es" indica que o nome da sua branch (head ref) contém caracteres especiais que foram codificados em Unicode. Especificamente, as sequências \u00E7, \u00E3 e \u00F5 representam letras acentuadas (respectivamente ç, ã e õ).
> 
> **Impacto**
> 
> **Codificação de Caracteres:** Alguns sistemas de controle de versão e ferramentas CI/CD preferem nomes de branch sem caracteres especiais, pois eles podem ser interpretados de forma diferente dependendo do sistema e do software.
> 
> **Compatibilidade e Erros Potenciais:** Isso pode causar problemas em algumas plataformas ou scripts automatizados que não processam corretamente caracteres Unicode em nomes de branch.

Isso foi problema do próprio Projects que criou a branch com o nome da Issue

2024-10-28 23:20 UTC, RafaelOsiro commented on MoneyManagement App/View/Components/Rows/ToggleRow.swift
> +                Text(LocalizedStringResource(stringLiteral: self.label))
Aqui era pra ser `LocalizeStringKey` ao invés de ser `LocalizedStringResource`
E que isso vai ser pra localizar um texto no aplicativo. Então, não. Não pode ser colocado diretamente o `self.label`.

2024-10-28 23:22 UTC, RafaelOsiro commented on MoneyManagement App/View/Components/Rows/ToggleRow.swift
> +    @Binding var toogleValue: Bool
Aqui não é uma Classe. E sim uma variável. Ela deve começar com letra minúscula.

2024-10-28 23:53 UTC, raquelsantoss commented
> > @RafaelOsiro outro ponto, não criar mais nomes de branchs que contenham acento: ![image](https://private-user-images.githubusercontent.com/80298086/380911889-d3129bb8-2148-434d-bfc4-4cef4ebd0fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTYwNDIsIm5iZiI6MTczMDE1NTc0MiwicGF0aCI6Ii84MDI5ODA4Ni8zODA5MTE4ODktZDMxMjliYjgtMjE0OC00MzRkLWJmYzQtNGNlZjRlYmQwZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIyNDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzM2MDMzZmMyNmIzOWI1ZjkzNDU4YWYxMmZhYWZlNTY0YmRmZDAyNWRkZTIxZmRhM2M5NDM1N2QxZmQ5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WnBHVs9hOAkJK2ljMUvxd6qWxagGVFlQvRhJmPTE-FM)
> > A mensagem "The head ref may contain hidden characters: "8-feature-implementa\u00E7\u00E3o-da-tela-de-configura\u00E7\u00F5es" indica que o nome da sua branch (head ref) contém caracteres especiais que foram codificados em Unicode. Especificamente, as sequências \u00E7, \u00E3 e \u00F5 representam letras acentuadas (respectivamente ç, ã e õ).
> > **Impacto**
> > **Codificação de Caracteres:** Alguns sistemas de controle de versão e ferramentas CI/CD preferem nomes de branch sem caracteres especiais, pois eles podem ser interpretados de forma diferente dependendo do sistema e do software.
> > **Compatibilidade e Erros Potenciais:** Isso pode causar problemas em algumas plataformas ou scripts automatizados que não processam corretamente caracteres Unicode em nomes de branch.
> 
> Isso foi problema do próprio Projects que criou a branch com o nome da Issue

Quando for assim, pode criar pelo próprio git e linkar na issue depois ou renomear.

2024-10-29 00:45 UTC, raquelsantoss approved these changes

2024-10-29 00:46 UTC, merged