Chore: Remover a Splash Screen em debug environment e excluir arquivos não usados
Swift-Money-Management-Team-App/MoneyManagementApp pull request #26
Opened 2024-10-29 02:27 UTC by RafaelOsiro

### Issue
closes #25

### Description
This PR aims to remove app `.gitignore` file that is not being used.
On the real `.gitignore` that is being used by git added swift template and add .DS_STORE file to be ignored
Add debug condition on main to check if it's debug environment the system will not build and display the Splash Screen

### File Change
- App .gitignore: Remove unused file
- .gitignore: Add Swift template and .DS_STORE
- Application-money-management_app-app: add debug environment

### Screenshot

2024-10-29 12:48 UTC, giovannifavorin commented
Since we are removing unused files, I recommend deleting the PersistenceController; this file isn't being used in the project.
<img width="100" alt="Captura de Tela 2024-10-29 às 09 45 47" src="https://github.com/user-attachments/assets/116efcb2-46e6-416f-af48-c169a70f38b8">

2024-10-30 23:19 UTC, raquelsantoss approved these changes

2024-10-30 23:40 UTC, giovannifavorin requested changes
Since we are removing unused files, I recommend deleting the PersistenceController; this file isn't being used in the project.

2024-10-31 00:02 UTC, RafaelOsiro commented
> Since we are removing unused files, I recommend deleting the PersistenceController; this file isn't being used in the project.

persistence controller was deleted when I refactor the database in PR #34

2024-10-31 00:07 UTC, giovannifavorin approved these changes

2024-10-31 00:13 UTC, merged