Feat/expenses view
Swift-Money-Management-Team-App/MoneyManagementApp pull request #44
Opened 2024-11-07 20:23 UTC by giovannifavorin

### Overview
Made Category flow

### Key Changes

- **View**: Made Views for adding, Editing, deleting and seeing data 
- **Model**: Connected with Model, saving data in SwiftData

### Screenshots

<img width="378" alt="Captura de Tela 2024-11-07 às 17 20 32" src="https://github.com/user-attachments/assets/f06ccbe7-a85f-4d9a-9f6a-b907293c3880">
<img width="364" alt="Captura de Tela 2024-11-07 às 17 20 42" src="https://github.com/user-attachments/assets/0388a4b1-4fcc-4c5c-a6c3-e7076508247e">
<img width="387" alt="Captura de Tela 2024-11-07 às 17 20 51" src="https://github.com/user-attachments/assets/adf475b5-ece8-406c-9834-af399ccca9e0">

2024-11-16 02:04 UTC, RafaelOsiro requested changes
Your branch is not updated with develop and have conflicts.

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/Model/ExpenseCategory.swift
> -    var idUser: UUID
Please lets follow the Database modeling. If you have some doubts about the modeling we could huddle the dev team to update the database. But do NOT remove the modeling before we have this discussion with the team.

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/DetailPaymentMethod/Component/EmojiPicker.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/DetailPaymentMethod/DetailPaymentMethod+View.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/DetailPaymentMethod/DetailPaymentMethod+ViewModel.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/EditPaymentMethod/EditPaymentMethod+View.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/EditPaymentMethod/EditPaymentMethod+ViewModel.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/PaymentMethod/PaymentMethod+ViewModel.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:04 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/TransactionCategories/TransactionAlertsTest.swift
> +//
Please remove the comments (lines 1 to 6)

2024-11-16 02:51 UTC, giovannifavorin commented on MoneyManagement App/Model/ExpenseCategory.swift
> -    var idUser: UUID
Can we schedule a moment to discuss on the necessity of this var? why is it necessary to connect those two data?

2024-11-20 05:50 UTC, RafaelOsiro requested changes
I found several bugs that are not following the prototype or the business rules. You might not be aware, but most of the prototype is interactive (this has been the case since I created it), and you could have seen more details by running the Figma preview.
Additionally, the section for adding a financial institution contains a lot of business logic that you could have reviewed as well.

## Bug 1
In the simulator video, when opening a payment method, a sheet (modal) is displayed showing the selected item's details in a read-only state. However, when clicking on "Edit," the data becomes editable. If no changes are made and the user decides to click the back button, the sheet should return to the Read-Only State as shown in the screenshot below. However, clicking the button currently dismisses the sheet. Fix this behavior so that, when editing, if the user makes no changes and clicks back, the sheet DOES NOT DISMISS and instead reverts to its original state.

https://github.com/user-attachments/assets/d671c4f1-2e85-4537-b9c8-c38e3c267501

<img width="256" alt="image" src="https://github.com/user-attachments/assets/2006eab6-a62f-42f4-90fb-a24ce4444c0f">

## Bug 2
The hitbox of the cell on the payment methods screen is too small.
This can be observed when I add a red border around the cell's outline.
Only the red-bordered area is selectable, while the rest of the cell is not clickable.

![image](https://github.com/user-attachments/assets/805cb6ea-fbc4-4b0c-b496-82092d2c6c41)

## Bug 3
3. The alert message for removing payment methods should be consistent. In **Image 1**, the alert shows both a title and a description. In **Image 2**, it only shows the title. **Image 3** from the prototype indicates that all alerts should be the same, using only the title without a description (both for deletion from the list and deletion when viewing the item).
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 02 00 02](https://github.com/user-attachments/assets/502cc365-f497-4a5c-b80e-2530c4cf7d10)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 02 00 07](https://github.com/user-attachments/assets/82111c63-3691-4721-8628-9355eac3b321)
<img width="409" alt="image" src="https://github.com/user-attachments/assets/f14fbe91-6e0b-412a-8906-435575f9251d">

## Bug 4
The slider button in the Earnings list is incorrect. It should only display the trash icon and not the "Delete" label.
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 02 08 21](https://github.com/user-attachments/assets/6f424a13-d304-4550-9974-0c9927a8d971)
<img width="280" alt="image" src="https://github.com/user-attachments/assets/0f55d792-827e-4cc0-8f7f-6cc58f14492f">

## Bug 5
The alert to confirm the deletion of an earnings item is missing.

https://github.com/user-attachments/assets/1220aec5-32bc-4168-b175-160e7eecf3a2

<img width="280" alt="image" src="https://github.com/user-attachments/assets/d2c90d13-0b24-4b67-9878-3d38f6a5d9a6">

## Bug 6
When trying to create a new earnings category, if the user does nothing and decides to cancel the addition, the alert should not be displayed.
This alert should only appear if the user is in the middle of editing and clicks the Cancel button.

https://github.com/user-attachments/assets/fde74a67-2488-4f25-8f13-5410880971af

## Bug 7 + Feature Request
The screen's appearance does not match the Figma prototype.
In the Figma screen, there are no rounded borders, and the form items span the entire width of the screen. Additionally, the text field is misaligned with the item above it.
The "Delete Earnings Category" button is not separated; it is grouped with all the other items on the screen.

This is not a bug, but the title can be updated to "Editar Categoria de Ganho". If the user turns off the `Ganho` toggle, the title should change to "Editar Categoria de Gasto".

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 02 16 36](https://github.com/user-attachments/assets/8a7f2b11-c870-484a-b6ef-63fe91d84406)
<img width="307" alt="image" src="https://github.com/user-attachments/assets/0738a278-9122-484d-acf7-d090fb04561a">

## Bug 8
When clicking the delete button for an item after opening the sheet, the confirmation alert for deletion does not appear.

https://github.com/user-attachments/assets/f3371398-12c1-430e-be32-1f17d9a67e85

<img width="368" alt="image" src="https://github.com/user-attachments/assets/9ce84809-cc55-4724-a583-efda59a7074b">

## Bug 9

1. The user can edit the name and toggle the switch, which should not be allowed in read-only mode.
2. The text and icon should have specific colors in read-only mode (the text opacity differs when adding or editing an earning).
3. The sheet title is incorrect.

https://github.com/user-attachments/assets/fe4cada9-857b-4687-b8e4-0b9d989bb525

<img width="319" alt="image" src="https://github.com/user-attachments/assets/81614170-9d90-43b1-9a02-c107bea2c956">

## Bug 10
When adding an Expense Category, the `Ganho` toggle should be disabled by default when the modal opens.
Similarly, for an Earnings Category, the `Ganho` toggle should be enabled by default when the modal opens.

https://github.com/user-attachments/assets/a9b51e8a-c166-4a7b-b78d-eea276d84d39

<img width="282" alt="image" src="https://github.com/user-attachments/assets/265c6e4a-8d56-4f4f-ad53-212f35f72858">

## Bug 11

1. On both the Earnings and Expense screens, the title size differs from the Figma prototype.
2. On the Expense sheet, the text is incorrect—it is in plural form when it should be singular.

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 02 40 44](https://github.com/user-attachments/assets/cb62f9c5-4e94-400b-8029-f7f174c9bca1)

<img width="364" alt="image" src="https://github.com/user-attachments/assets/54f59efe-5eab-4313-9a5e-967d7db3f6df">

![image](https://github.com/user-attachments/assets/69548df1-9926-468f-a650-820d4bd42048)

<img width="282" alt="image" src="https://github.com/user-attachments/assets/d2baad70-5825-4f5b-b0d4-0ffed09b90a8">

## Bug 12
On the Expenses screen, the same bugs occurring on the Earnings screen are present. Here's the list of issues that need to be fixed for the Expenses section:
Bug 4: The slider button should only display the trash icon and not the "Delete" label.
Bug 5: The confirmation alert for item deletion is missing when clicking the delete button.
Bug 6: In read-only mode, the user can edit fields and toggle switches, which should not be allowed. The text and icon should have appropriate colors for read-only mode.
Bug 7 + Feature Request: The screen title should match the Figma prototype's font size and content. Additionally, if the toggle Earnings is turned off, the title should dynamically update to "Edit Expense Category."
Bug 8: The toggle Earnings should be disabled by default when adding an Expense Category.
Bug 9: The sheet title is in plural form, which is incorrect; it should be singular.

2024-11-27 22:15 UTC, closed without merging