Feat: Payment method screen
Swift-Money-Management-Team-App/MoneyManagementApp pull request #45
Opened 2024-11-09 19:29 UTC by raquelsantoss

### Issue
closes #32 
closes #33 

### Overview
This PR includes the creation and integration of three main views for managing payment methods within the app. These views allow users to add, edit, view details, and delete payment methods while ensuring that data consistency is maintained and appropriate validations are applied.

### Key Changes

- **PaymentMethodView**: Main screen that lists all payment methods. Users can tap on a payment method to view its details or swipe to delete, with validation to prevent deletion if transactions are associated.
  
- **DetailPaymentMethodView**: Detail view for a selected payment method. Users can view the method name and icon, with options to edit or delete. This view includes a check for associated transactions before enabling deletion.

- **EditPaymentMethodView**: Form view to add or edit a payment method. Allows selection of an icon and entry of a method name. The icon selector includes a paginated grid layout, and the save/cancel actions are validated to prevent empty fields.

2024-11-10 17:00 UTC, CaioVicenzi commented
![image](https://github.com/user-attachments/assets/7bc0be17-d601-4863-9ade-6bb6c29bc096)

Instead of using lots of private state variables, it's a good practice in the MVVM architecture to use a ViewModel to store all the properties that's going to update the view as a @Published var.

![image](https://github.com/user-attachments/assets/be0958dc-09bb-4adb-bb43-b3527aefd442)

There is some logic in the view that could be inside a ViewModel.

![image](https://github.com/user-attachments/assets/89cc81d3-ce60-48f3-9607-00d99366f39c)

This could be a Button instead of a HStack because it would allow the payment method to be taped anywhere within the list item.

You can also make the List to be right below the header, even with one or few payment methods added, that would make the app more consistent to the prototype.

2024-11-11 00:22 UTC, RafaelOsiro requested changes
1. Let's try to avoid open alert when user **add** a payment method and he didn't update nothing and when he try to cancel.
2. Let's try to avoid open alert when user **edit** a payment method and he didn't update nothing and when he try to cancel. 
3. Let's avoid to open 2 sheets. When user click in a method payment he and he can read all info of that method payment. When user click to edit you open a sheet. To avoid that, try to create a state when the form is reading and is editing and is adding.

https://github.com/user-attachments/assets/70e3aa3b-19a0-44f2-b355-9c262708f4b9


https://github.com/user-attachments/assets/d2396296-8f08-43b8-9456-82cf782025de

2024-11-11 00:22 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/PaymentMethod/DetailPaymentMethodView.swift
> +                .alert("Excluir Método de Pagamento?", isPresented: $showDeleteAlert) {
@raquelsantoss let's use the same alert when we use the delete button on List. You can copy and replace here.

<img width="306" alt="Captura de Tela 2024-11-10 às 21 07 39" src="https://github.com/user-attachments/assets/b56959fb-5ca2-44d1-9058-1d21cea40af2">

2024-11-11 02:11 UTC, RafaelOsiro requested changes
When I tried to update something and after that, the "Voltar" button is not calling the alert

https://github.com/user-attachments/assets/a4dab4d2-fd74-4306-80e2-84f073a20057


Try to use the same alert we use in list on the Edit View

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-10 at 23 10 25](https://github.com/user-attachments/assets/01c2ac15-98fb-49cd-87ba-b7c5733a76c5)

2024-11-11 11:49 UTC, raquelsantoss commented
> When I tried to update something and after that, the "Voltar" button is not calling the alert
> 
>  Simulator.Screen.Recording.-.iPhone.16.Pro.Max.-.2024-11-10.at.23.08.03.mp4 
> 
> Try to use the same alert we use in list on the Edit View
> 
> ![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-10 at 23 10 25](https://private-user-images.githubusercontent.com/79678821/384756963-01c2ac15-98fb-49cd-87ba-b7c5733a76c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUwOTUsIm5iZiI6MTczMTMyNDc5NSwicGF0aCI6Ii83OTY3ODgyMS8zODQ3NTY5NjMtMDFjMmFjMTUtOThmYi00OWNkLTg3YmEtYjdjNTczM2E3NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOGFhZmYzZjZhZDBkNjk1MTUwZjhlNTMzYjcyMTA3YzgwNTZkYTg0ZGMzYjE2YmJmMjFhOGRlY2M1MzRjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1MvF4X0Z_vCJbidqtyvMk0X-LD8pOWDnqqntgnZ2o24)
> 
> <img alt="image" width="272" src="https://private-user-images.githubusercontent.com/79678821/384757478-431f140c-bcba-455a-ba17-052566d973f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUwOTUsIm5iZiI6MTczMTMyNDc5NSwicGF0aCI6Ii83OTY3ODgyMS8zODQ3NTc0NzgtNDMxZjE0MGMtYmNiYS00NTVhLWJhMTctMDUyNTY2ZDk3M2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNjQwYTNjMjE2MWZiMTJjMDdlZWVhNGYzMjVlZDExMDNhNWUwZjE0ZmRiNDYxNmQyNWI5NGQ4ZDFiYmJkOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAebAPRDDwDcTdfLkAYsD-ZbRQuwN_TU2QA0TGqgdFY">

Actually, this alert should appear in the edit view, immediately after the detail page, as that’s where the user is updating the data. When returning to the detail view, they should only be in view mode.

2024-11-11 16:52 UTC, giovannifavorin approved these changes

2024-11-11 23:17 UTC, RafaelOsiro approved these changes
LGTM !

2024-11-11 23:17 UTC, merged