Feat(bank view) data integration
Swift-Money-Management-Team-App/MoneyManagementApp pull request #47
Opened 2024-11-10 20:09 UTC by CaioVicenzi

### Issue

Finishing the bank account detailing.

### Overview

This PR aims to finish doing my BankView task, the detailing of the BankAccount and the editing of its name, as well as the deletion, its goal is to fulfill all these objectives.

### Key Changes

- **<change-in-files>**: I was using the wrong file to mount this view, but I changed it to the correct file now.

- **total-calculation**: There is now a calculation behind the total money in all accounts of the financial institution's account.

- **back-button**: Now the back button only comes back with a warning if the name is different from the one saved in the bank.

2024-11-11 02:09 UTC, giovannifavorin commented
that view isn't connected to the app navigation

2024-11-11 02:09 UTC, giovannifavorin requested changes
Connect that view to the app navigation

2024-11-14 02:34 UTC, RafaelOsiro requested changes
You have a conflict in your branch.

Please update your branch with develop and solve those comments that I leave in my Review.
If you have something to discuss, please start a discussion in the comment

2024-11-14 02:34 UTC, RafaelOsiro commented on MoneyManagement App/View/Shared/Rows/Header.swift
> +//
Please remove the comments between lines 1 to 6

2024-11-14 02:34 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/Finances/BankView/BankViewModel.swift
> +//
Please remove the comments between lines 1 to 6

2024-11-14 02:34 UTC, RafaelOsiro commented on MoneyManagement App/View/Views/Finances/Components/Balance.swift
> +//
Please remove the comments between lines 1 to 6

2024-11-14 23:32 UTC, closed without merging